/**
 * Represents a user-generated asset, which can be a character or an environment.
 */
export interface IAsset {
  id: string;
  name: string;
  type: 'character' | 'environment';
  prompt: string;
  imageUrl: string; // URL to the generated image
}

/**
 * Represents a single generated manga page.
 */
export interface IMangaPage {
  id:string;
  pageNumber: number;
  prompt: string;
  imageUrl: string; // URL to the generated manga page image
}

/**
 * Represents a high-level plan for the entire manga story, generated by AI.
 */
export interface IStoryPlan {
  detailedStorySummary: string;
  detailedArtStyle: string;
  characters: {
    name: string;
    description: string;
  }[];
  environments: {
    name: string;
    description: string;
  }[];
  pages: {
    page: number;
    description: string; // This will now be a more detailed plot point
  }[];
}

// IProjectState is no longer needed as we manage state in the root component
